import Header from "@/Components/Header";
import "./globals.css";
import Footer from "@/Components/footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="h-screen bg-gradient-to-r from-slate-300 to-slate-500">
        <Header/>
        {children}
        <Footer/>
        </div>
      </body>
    </html>
  );
}
