import Header from "@/components/Header";
import "./globals.css";
import Footer from "@/components/footer";
import AuthProvider from "@/context/authprovider";
import QueryProvider from "@/context/queryProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}){

  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <QueryProvider>
        <div className="h-full bg-gradient-to-r from-slate-300 to-slate-500">
         <Header />
          {children}
        </div>
        <Footer />
        </QueryProvider>
        </AuthProvider>
      </body>
    </html>
  )
  }
